### ISSUE TITLE
Basetool should respect the next

### ISSUE THREAD

**Issue by vernonstinebaker** [basetool-io/basetool#382]
**Describe the bug**
When configuring the application to run internally, without a canonical URL, the application loops displaying:
    https://next-auth.js.org/errors#client_fetch_error session TypeError: Only absolute URLs are supported

**To Reproduce**
Configure .env to use a local IP, localhost, etc as the NEXTAUTH_URL

or

Comment out NEXTAUTH_URL and add NEXTAUTH_URL_INTERNAL

the application will indicate that NEXTAUTH_URL is not set and will continue to issue the error:
https://next-auth.js.org/errors#client_fetch_error session TypeError: Only absolute URLs are supported

**Expected behavior**
When NEXTAUTH_URL_INTERNAL is set the application should respect this configuration.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker container
 - Browser Safari 
 - Version 15.4

**Additional context**
![Screen Shot 2022-04-15 at 2 50 11 PM](https://user-images.githubusercontent.com/8304954/163532992-28420a0d-a409-4696-be7d-a49a2458e015.png)
![Screen Shot 2022-04-15 at 2 49 03 PM](https://user-image
![Screen Shot 2022-04-15 at 2 48 25 PM](https://user-images.githubusercontent.com/8304954/163533026-d36a89d1-6045-4df2-886d-ca32d0a68ec4.png)
s.githubusercontent.com/8304954/163533016-5eac08e3-bac8-4d83-9f94-945c6bd2bc59.png)

**Comment by adrianthedev** [comment]
Hey @vernonstinebaker. Unfortunately, we don't have too much time allocation for basetool at the moment.

We're open to merging in a PR if you're so kind as to invest a bit of your time. Thank  you!
